export const GET_LIST_TODO_SUCCESS = 'GET_LIST_TODO_SUCCESS'
export const GET_LIST_TODO_ERROR = 'GET_LIST_TODO_ERROR'
export const POST_TODO_SUCCESS = 'POST_TODO_SUCCESS'
export const GET_DETAIL_TODO_SUCCESS = 'GET_DETAIL_TODO_SUCCESS'
export const PUT_TODO_SUCCESS = 'PUT_TODO_SUCCESS'

export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS'
export const POST_LOGIN_LOADING = 'POST_LOGIN_LOADING'
export const POST_LOGIN_ERROR = 'POST_LOGIN_ERROR'