export const GET_LIST_TODO_SUCCESS = 'GET_LIST_TODO_SUCCESS'
export const GET_LIST_TODO_ERROR = 'GET_LIST_TODO_ERROR'
export const POST_TODO_SUCCESS = 'POST_TODO_SUCCESS'
export const GET_DETAIL_TODO_SUCCESS = 'GET_DETAIL_TODO_SUCCESS'
export const PUT_TODO_SUCCESS = 'PUT_TODO_SUCCESS'

export const ON_SUCCESS = 'ON_SUCCESS'
export const ON_LOADING = 'ON_LOADING'
export const ON_ERROR = 'ON_ERROR'

export const SHOW_HIDE_MODAL = 'SHOW_HIDE_MODAL'
